In [1]:
# Topics:

# LogisticRegression

# Working of LogisticRegression

# Train model on logistic Regression

# calculate training and testing score

# calculate classification report for training and testing dataset



In [2]:
# LogisticRegression:

In [3]:
from sklearn.linear_model import LogisticRegression

In [6]:
import pandas as pd

In [8]:
df=pd.read_csv("Fruit_dataset_10000.csv")

In [16]:
df['name'].value_counts()  # we will use classification beacuse target belong to only two class

orange        5000
grapefruit    5000
Name: name, dtype: int64

In [21]:
# Now we will break dataset df into two part feature called X and target called y
X=df.iloc[:,1:].values
y=df.iloc[:,0].values

In [23]:
X

array([[  2.96,  86.76],
       [  3.91,  88.05],
       [  4.42,  95.17],
       ...,
       [ 15.59, 256.5 ],
       [ 15.92, 260.14],
       [ 16.45, 261.51]])

In [24]:
# scaling 
from sklearn.preprocessing import MinMaxScaler

In [25]:
sc=MinMaxScaler()

In [27]:
X_sc=sc.fit_transform(X)

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X_sc,y)

In [30]:
X_train.shape

(7500, 2)

In [31]:
y_train.shape

(7500,)

In [32]:
X_test.shape

(2500, 2)

In [33]:
y_test.shape

(2500,)

In [34]:
Model=LogisticRegression()

In [35]:
Model.fit(X_train,y_train)

LogisticRegression()

In [38]:
X_train_pred=Model.predict(X_train)

In [39]:
y_train

array(['grapefruit', 'orange', 'grapefruit', ..., 'grapefruit',
       'grapefruit', 'orange'], dtype=object)

In [40]:
from sklearn.metrics import accuracy_score

In [41]:
accuracy_score(y_train,X_train_pred)

0.8808

In [45]:
X_test_pred=Model.predict(X_test)

In [46]:
y_test

array(['grapefruit', 'orange', 'orange', ..., 'orange', 'grapefruit',
       'orange'], dtype=object)

In [49]:
accuracy_score(y_test,X_test_pred)

0.8856

In [50]:
Model.score(X_train,y_train)

0.8808

In [51]:
Model.score(X_test,y_test)

0.8856

In [52]:
from sklearn.metrics import classification_report

In [55]:
print(classification_report(y_train,X_train_pred))

              precision    recall  f1-score   support

  grapefruit       0.88      0.88      0.88      3744
      orange       0.88      0.88      0.88      3756

    accuracy                           0.88      7500
   macro avg       0.88      0.88      0.88      7500
weighted avg       0.88      0.88      0.88      7500



In [57]:
Model.coef_

array([[-12.64951191,  -8.64349299]])

In [58]:
Model.intercept_

array([10.95966369])

In [66]:
print(X_train[0])
print(y_train[0])
print(Model.coef_)
print(Model.intercept_)

[0.57894737 0.56972818]
grapefruit
[[-12.64951191  -8.64349299]]
[10.95966369]


In [67]:
# y=m1x1+m2x2+c
y=-12.64951191*0.57894737+(-8.64349299)*0.56972818+10.95966369
print(y)

-1.2881794921136347


In [68]:
# probability using sigmoid function if p<0.5 then class 0 or 1

# P[1]=1/(1+e**(-y))
#P[0]=1/(1+e**(y))

In [78]:
 import math
 P=1/(1+2.718281828459045**(-(-1.2881794921136347)))

In [79]:
print(P)

0.21616111006548228


In [80]:
math.e

2.718281828459045

In [81]:
X_train.pred

AttributeError: 'numpy.ndarray' object has no attribute 'pred'

In [82]:
Model.predict([[0.57894737, 0.56972818]])

array(['grapefruit'], dtype=object)

In [87]:
X_train_pred[:10]

array(['grapefruit', 'orange', 'grapefruit', 'grapefruit', 'grapefruit',
       'grapefruit', 'grapefruit', 'grapefruit', 'grapefruit',
       'grapefruit'], dtype=object)

In [88]:
y_train[:10]

array(['grapefruit', 'orange', 'grapefruit', 'grapefruit', 'grapefruit',
       'orange', 'grapefruit', 'grapefruit', 'grapefruit', 'orange'],
      dtype=object)

In [85]:
X_test_pred

array(['grapefruit', 'orange', 'grapefruit', ..., 'orange', 'grapefruit',
       'orange'], dtype=object)

In [86]:
y_test

array(['grapefruit', 'orange', 'orange', ..., 'orange', 'grapefruit',
       'orange'], dtype=object)

In [89]:
print(X_train[5])
print(y_train[5])
print(Model.coef_)
print(Model.intercept_)

[0.62194218 0.61470672]
orange
[[-12.64951191  -8.64349299]]
[10.95966369]


In [91]:
y=(-12.64951191)* 0.62194218+(-8.64349299)*0.61470672+10.95966369
y

-2.2208145484672563

In [93]:
 import math
 P=1/(1+2.718281828459045**(-(-2.2208145484672563)))
 P

0.09789684547062191

In [94]:
Model.predict([[0.62194218,0.61470672]])

array(['grapefruit'], dtype=object)